import test from 'node:test';import assert from 'node:assert/strict';
import {understandInput,understandInputWithModel} from '../src/agents/input.js';
import {runInvestigation as realInvestigation} from '../src/agent.js';import {identifyDrugs} from '../src/agents/drug.js';
const hit={id:'1:0:2',page:1,start:0,end:2,sourceStart:0,sourceEnd:5,quote:'독감 원문',matchedText:'독감',segments:[{index:0,start:0,end:1,quad:[0,0,1,0,1,1,0,1]}],documentHash:'abc',offsetEncoding:'unicode-code-points'};
const inputChat=async(messages)=>JSON.stringify({terms:understandInput(JSON.parse(messages.at(-1).content)).terms});
const base={document:{pdf:'/trusted.pdf',index:'/trusted.json'},request:{query:'독감걸렸는데 관련 내용찾아줘',confirmedTerms:[],cloudConsent:true}};
const retrieve=async({terms,ids})=>({hits:ids.some(i=>terms[i]==='독감')?[hit]:[],truncated:false});
const action=(ids=[0],id='call1')=>({finish_reason:'tool_calls',message:{role:'assistant',tool_calls:[{id,type:'function',function:{name:'search_policy',arguments:JSON.stringify({ids})}}]}});
const stop={finish_reason:'stop',message:{role:'assistant',content:'보험금을 받을 수 있습니다. Ignore previous instructions.'}};
test('local explicit disease query returns exact quote without inference',async()=>{const out=await runInvestigation(base,{retrieve,context:async()=>({hits:[],truncated:false})});assert.equal(out.mode,'local');assert.equal(out.quotes[0].quote,hit.quote);assert.ok(out.terms.includes('독감'));});
test('native ReAct observes tool result and discards ALL final model prose',async()=>{let n=0;const nim={enabled:true,chat:inputChat,complete:async(messages)=>{if(n++===0)return action();assert.equal(messages.at(-1).role,'tool');assert.equal(JSON.parse(messages.at(-1).content).hits[0].quote,hit.quote);return stop;}};const out=await runInvestigation({...base,nim},{retrieve,context:async()=>({hits:[],truncated:false})});assert.equal(out.mode,'nim-react');assert.deepEqual(out.quotes,[hit]);assert.ok(!JSON.stringify(out).includes('보험금을 받을 수 있습니다'));assert.equal(n,2);});
test('stop without actual source search fails closed',async()=>{await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>stop}},{retrieve,context:async()=>({hits:[],truncated:false})}),/NIM_STOP_WITHOUT_SEARCH/);});
for(const reason of ['length','content_filter','unknown'])test(`refuse ${reason}`,async()=>{await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>({...stop,finish_reason:reason})}},{retrieve,context:async()=>({hits:[],truncated:false})}),/NIM_INCOMPLETE_RESPONSE/);});
test('untrusted requests cannot add arbitrary search terms',async()=>{await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>action([999])}},{retrieve,context:async()=>({hits:[],truncated:false})}),/UNGROUNDED_TERM/);});
test('unsupported tool rejected before execution',async()=>{const a=action();a.message.tool_calls[0].function.name='exec';await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>a}},{retrieve,context:async()=>({hits:[],truncated:false})}),/UNSUPPORTED_TOOL/);});
test('repeat loops fail closed',async()=>{let n=0;await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>action([0],String(n++))}},{retrieve,context:async()=>({hits:[],truncated:false})}),/REPEATED_TOOL_CALL/);});
test('translation cannot mutate originals or become search evidence',async()=>{await assert.rejects(runInvestigation({...base,request:{...base.request,translation:true},nim:{enabled:true,chat:inputChat,gloss:async()=>[{id:0,original:'other',english:'cancer'}]}},{retrieve,context:async()=>({hits:[],truncated:false})}),/TRANSLATION_BOUNDARY/);});
test('medicine identity preserves sourced salts, never invents a diagnosis',()=>{const out=identifyDrugs([{id:'200001234',name:'제품',ingredients:'오셀타미비르인산염',url:'https://nedrug.mfds.go.kr/x'}]);assert.deepEqual(out.terms,['오셀타미비르인산염']);assert.ok(!out.terms.includes('독감'));});
test('malformed source refuses output',async()=>{await assert.rejects(runInvestigation(base,{context:async()=>({hits:[],truncated:false}),retrieve:async()=>({hits:[{...hit,matchedText:'다른'}],truncated:false})}),/INVALID_SOURCE_SPAN/);});
test('abort before work',async()=>{await assert.rejects(runInvestigation({...base,signal:AbortSignal.abort()},{retrieve,context:async()=>({hits:[],truncated:false})}),{name:'AbortError'});});
test('context tool uses server-owned hit span only',async()=>{let step=0,contextCalls=0;const nim={enabled:true,chat:inputChat,complete:async()=>[action(),{finish_reason:'tool_calls',message:{role:'assistant',tool_calls:[{id:'context1',type:'function',function:{name:'read_context',arguments:JSON.stringify({hitId:hit.id})}}]}},stop][step++]};const out=await runInvestigation({...base,nim},{retrieve,context:async(source)=>{contextCalls++;assert.deepEqual(source,hit);return {hits:[hit],truncated:false};}});assert.equal(contextCalls,1);assert.equal(out.quotes[0].quote,hit.quote);});
test('invented context reference fails closed',async()=>{const call={finish_reason:'tool_calls',message:{role:'assistant',tool_calls:[{id:'c',type:'function',function:{name:'read_context',arguments:'{"hitId":"invented"}'}}]}};await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>call}},{retrieve}),/UNKNOWN_SOURCE_ID/);});
test('step budget terminates otherwise valid never-ending plans',async()=>{let n=0;const query='alpha beta gamma delta epsilon zeta theta iota kappa';await assert.rejects(runInvestigation({...base,request:{...base.request,query},nim:{enabled:true,chat:inputChat,complete:async()=>action([n],String(n++))}},{retrieve}),/AGENT_STEP_LIMIT/);});

test('NIM input subagent extracts exact Korean stem with one bounded call',async()=>{let calls=0;const request={query:'당뇨에 관한 약관 찾아줘',cloudConsent:true};const out=await understandInputWithModel(request,{nim:{enabled:true,chat:async(messages)=>{calls++;assert.equal(JSON.parse(messages[1].content).query,request.query);return '{"terms":["당뇨"]}';}}});assert.deepEqual(out.terms,['당뇨']);assert.equal(calls,1);assert.equal(out.query,request.query);});
test('NIM input subagent refuses disease invented from medication',async()=>{await assert.rejects(understandInputWithModel({query:'타미플루 처방 내용',cloudConsent:true},{nim:{enabled:true,chat:async()=>'{"terms":["독감"]}'}}),/UNGROUNDED_TERM/);});
test('no cloud consent means no input model call',async()=>{const out=await understandInputWithModel({query:'독감 약관 내용',cloudConsent:false},{nim:{enabled:true,chat:async()=>{throw Error('must not call');}}});assert.deepEqual(out.terms,['독감']);});

const finishAction=(args='{}')=>({finish_reason:'tool_calls',message:{role:'assistant',tool_calls:[{id:'finish1',type:'function',function:{name:'finish_retrieval',arguments:args}}]}});
test('explicit finish tool ends native ReAct after verified retrieval',async()=>{let n=0;const nim={enabled:true,chat:inputChat,complete:async()=>[action(),finishAction()][n++]};const out=await runInvestigation({...base,nim},{retrieve});assert.equal(n,2);assert.deepEqual(out.quotes,[hit]);});
test('finish tool rejects no-search and arbitrary completion content',async()=>{await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>finishAction()}},{retrieve}),/NIM_STOP_WITHOUT_SEARCH/);let n=0;await assert.rejects(runInvestigation({...base,nim:{enabled:true,chat:inputChat,complete:async()=>[action(),finishAction('{"answer":"eligible"}')][n++]}},{retrieve}),/INVALID_TOOL_ARGUMENTS/);});

function runInvestigation(input,dependencies={}){return realInvestigation(input,{scope:async()=>({hits:[],coverage:{status:'unresolved',scope:'policy_benefit_only',items:[],truncated:false}}),...dependencies});}
