import test from 'node:test';import assert from 'node:assert/strict';
import {describePolicyScope} from '../src/agents/policy-scope.js';
import {resolveDrugReferences} from '../src/agents/drug-references.js';
import {assembleEvidence} from '../src/agents/verification.js';
const source=(id,quote)=>({id,page:1,start:0,end:Array.from(quote).length,sourceStart:0,sourceEnd:Array.from(quote).length,quote,matchedText:quote,segments:[],documentHash:'test',offsetEncoding:'unicode-code-points'});
const refs=()=>resolveDrugReferences({description:'조플루자'}).references;
function rider({payment='인플루엔자 치료 목적으로 처방받은 경우 보험금을 지급합니다.',definition='성분명: 발록사비르(baloxavir)',title='6-36 독감(인플루엔자) 특별약관'}={}){const t=source('title',title),p=source('payment',payment),d=source('definition',definition),e=source('exclusion','보통약관 제8조에 따릅니다.');return {id:t.id,title:t,clauses:[{kind:'payment',heading:p,hits:[p]},{kind:'definition',heading:d,hits:[d]},{kind:'exclusion',heading:e,hits:[e]}],truncated:false};}
test('policy benefit and cited ingredient bridge are distinguished from actual eligibility',()=>{const coverage=describePolicyScope({sections:[rider()],references:refs(),terms:['조플루자']});assert.equal(coverage.status,'identified');assert.equal(coverage.scope,'policy_benefit_only');assert.equal(coverage.items[0].links[0].kind,'ingredient');assert.equal(coverage.items[0].links[0].term,'발록사비르');assert(coverage.items[0].checks.some(c=>c.kind==='cross_reference'));assert(coverage.items[0].checks.every(c=>c.status==='needs_confirmation'));assert(!('eligible' in coverage));});
test('a heading, an exclusion-only match and an unrelated indication cannot become benefit confirmation',()=>{for(const section of [rider({payment:'제1조 (보험금의 지급사유)'}),rider({definition:'발록사비르는 보장하지 않습니다.'}),rider({title:'6-36 암 특별약관',payment:'암 진단 시 지급합니다.'})]){assert.equal(describePolicyScope({sections:[section],references:refs(),terms:['조플루자']}).status,'unresolved');}});
test('direct product wording and explicit disease term have separate connection labels',()=>{const direct=describePolicyScope({sections:[rider({definition:'조플루자 약품명 안내'})],references:refs(),terms:['조플루자']});assert.equal(direct.items[0].links[0].kind,'direct_brand');const explicit=describePolicyScope({sections:[rider()],terms:['인플루엔자']});assert.equal(explicit.items[0].links[0].kind,'explicit_term');});
test('source facts cannot be forged and coverage IDs must belong to returned original spans',()=>{const references=refs();references[0].facts[0].quote='invented';assert.throws(()=>describePolicyScope({sections:[rider()],references}),/UNVERIFIED_DRUG_REFERENCE/);const coverage=describePolicyScope({sections:[rider()],references:refs(),terms:['조플루자']});assert.throws(()=>assembleEvidence({hits:[],mappings:[],references:refs(),terms:[],mode:'local',truncated:false,coverage}),/INVALID_COVERAGE_SOURCE/);});
test('blank or invisible source blocks are removed without trimming valid quotes',()=>{const visible=source('visible','  독감 원문\n');const r=assembleEvidence({hits:[source('blank','  \n'),source('invisible','\u200b\ufeff'),visible],mappings:[],terms:[],mode:'local',truncated:false});assert.deepEqual(r.quotes,[visible]);assert.equal(r.quotes[0].quote,'  독감 원문\n');});
