import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {Nvidia,Drugs} from '../src/providers.js';
const response=x=>new Response(JSON.stringify(x),{status:200});
test('NIM preserves tool protocol and supplies tool schema',async()=>{let request;const nim=new Nvidia({key:'test',base:'https://example.test/v1'},async(u,o)=>{request=JSON.parse(o.body);return response({choices:[{finish_reason:'tool_calls',message:{role:'assistant',content:null,tool_calls:[{id:'t1',type:'function',function:{name:'search',arguments:'{}'}}]}}]});});const result=await nim.complete([{role:'user',content:'독감'}],{tools:[{type:'function',function:{name:'search',parameters:{type:'object'}}}]});assert.equal(request.messages[0].content,'독감');assert.equal(result.finish_reason,'tool_calls');assert.equal(request.tools[0].function.name,'search');});
test('OCR uses documented input array, retains Unicode and requires confirmation',async()=>{const image=await sharp({create:{width:10,height:10,channels:3,background:'white'}}).png().toBuffer();let payload;const nim=new Nvidia({key:'test',ocrUrl:'https://example.test/v1/ocr'},async(u,o)=>{payload=JSON.parse(o.body);return response({data:[{text_detections:[{text_prediction:{text:'타미플루 75mg',confidence:.8},bounding_box:{points:[]}}]}]});});const r=await nim.ocr(image);assert.equal(r.text,'타미플루 75mg');assert.equal(r.requiresConfirmation,true);assert.equal(payload.input[0].type,'image_url');assert.match(payload.input[0].url,/^data:image\/png;base64,/);assert.deepEqual(payload.merge_levels,['paragraph']);});
test('MFDS parses official v08 fields without changing ingredient names',async()=>{let url;const d=new Drugs('secret',(u)=>{url=new URL(u);return Promise.resolve(response({header:{resultCode:'00'},body:{items:[{ITEM_SEQ:'200001234',ITEM_NAME:'테스트제품',ITEM_INGR_NAME:'원료 A|원료 B',ENTP_NAME:'제조원'}],totalCount:1}}));});const r=await d.lookup('테스트');assert.match(url.pathname,/Service08\/getDrugPrdtPrmsnInq08$/);assert.equal(url.searchParams.get('item_name'),'테스트');assert.equal(r.products[0].ingredients,'원료 A|원료 B');assert.equal(r.requiresSelection,true);assert(!JSON.stringify(r).includes('secret'));});
test('MFDS malformed/unauthorized response does not become no-match',async()=>{const d=new Drugs('x',async()=>response({header:{resultCode:'30'}}));await assert.rejects(()=>d.lookup('제품'),/MFDS_REQUEST_FAILED/);});
test('No credentials do not create fake API results',async()=>{const n=new Nvidia({});n.key='';await assert.rejects(()=>n.chat([]),/NVIDIA_KEY_REQUIRED/);const d=new Drugs('');await assert.rejects(()=>d.lookup('제품'),/MFDS_KEY_REQUIRED/);});

for(const [status,code] of [[410,'NIM_MODEL_UNAVAILABLE'],[404,'NIM_MODEL_UNAVAILABLE'],[401,'NIM_AUTH_FAILED'],[403,'NIM_AUTH_FAILED'],[429,'NIM_RATE_LIMIT'],[503,'NIM_SERVICE_UNAVAILABLE']])test(`NIM HTTP ${status} produces actionable error without provider body`,async()=>{const nim=new Nvidia({key:'test'},async()=>new Response('secret upstream details',{status}));await assert.rejects(()=>nim.chat([]),error=>error.message===code&&!error.message.includes('secret'));});
test('bounded Nemotron control requests disable thinking and validate chat finish_reason',async()=>{let body;const nim=new Nvidia({key:'test',model:'nvidia/nemotron-3.5-lightning-30b-a3b'},async(u,o)=>{body=JSON.parse(o.body);return response({choices:[{finish_reason:'stop',message:{content:'{"terms":["조플루자"]}'}}]});});assert.equal(await nim.chat([{role:'user',content:'제품명: 조플루자'}]),'{"terms":["조플루자"]}');assert.equal(body.chat_template_kwargs.enable_thinking,false);assert.deepEqual(body.response_format,{type:'json_object'});});
test('incomplete chat response cannot masquerade as successful JSON extraction',async()=>{for(const reason of ['length','content_filter']){const nim=new Nvidia({key:'test'},async()=>response({choices:[{finish_reason:reason,message:{content:'{"terms":[]}'}}]}));await assert.rejects(()=>nim.chat([]),/NIM_INCOMPLETE_RESPONSE/);}});
test('caller cancellation remains cancellation',async()=>{const signal=AbortSignal.abort();const nim=new Nvidia({key:'test'},async()=>{throw Error('abort');});await assert.rejects(()=>nim.chat([],{signal}),/CANCELLED/);});
test('optional non-Nemotron translation model receives no Nemotron-only options',()=>{const nim=new Nvidia({key:'test'});assert.deepEqual(nim.generationOptions('other/vendor-model'),{});});

test('invalid model JSON is typed and never repaired',async()=>{const nim=new Nvidia({key:'test'},async()=>response({choices:[{finish_reason:'stop',message:{content:'Here is JSON: {"terms":[]}'}}]}));await assert.rejects(()=>nim.chat([]),/NIM_INVALID_JSON/);});
